version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:19.0.2
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run: java --version
      - run: mvn clean install

workflows:
  version: 2
  build:
    jobs:
      - build